### ISSUE TITLE
Fix making several requests to the same campaign by same user

### ISSUE THREAD

**Issue by emadunan** [emadunan/arab-deals#14]
**As a** publisher 
 **I need** ability to make another request to the same campaign I already have some of its coupons
 **So that** I can receive new coupons
   
 ### Details and Assumptions
 * Only if the old request is resolved by decline or accept
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given an already assigned campaign to a specific user with the status accepted
 When that same user makes another request
 Then the campaign status changed to pending and a request was sent to the admin
 ```

**Comment by marcomagdy9** [comment]
tested. good job. thanks
